import streamlit as st
import cv2
import torch
import numpy as np
from PIL import Image

# Page config
st.set_page_config(layout="wide", page_title="Kineura Frame Predictor")

# Load model
@st.cache_resource
def load_model():
    # TODO
    # model = ModelClass()
    # model.load_state_dict(torch.load('best_weights.pth'))
    # model.eval().to('cuda')
    return "Model Loaded" # Placeholder

# Video handling
video_file = st.sidebar.file_uploader("Upload Video", type=['mp4', 'mov', 'avi'])

if video_file:
    # Save uploaded file locally to read with OpenCV
    with open("temp_video.mp4", "wb") as f:
        f.write(video_file.read())
    
    cap = cv2.VideoCapture("temp_video.mp4")
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # Top section: Triplet slider
    st.header("Step-by-Step Triplet Validation")
    idx = st.slider("Select Triplet Start Frame", 0, total_frames - 3, 0)

    # Grab a triplet
    frames = []
    for i in range(idx, idx + 3):
        cap.set(cv2.CAP_PROP_POS_FRAMES, i)
        ret, frame = cap.read()
        if ret:
            frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

    # Display triplet
    col1, col2, col3 = st.columns(3)
    with col1:
        st.image(frames[0], caption="Frame 1 (Input)")
    with col2:
        st.image(frames[1], caption="Frame 2 (Input)")
    with col3:
        # TODO
        # Placeholder for Prediction Logic
        # pred = model.predict(frames[0], frames[1])
        st.image(frames[2], caption="Frame 3 (Ground Truth)")
        st.image(frames[2], caption="Frame 3 (AI Predicted)") # Replace with 'pred', keeping the same as frame 3 for now

    st.divider()

    # Bottom half: Before and after videos
    st.header("Final Video Comparison")
    c_vid1, c_vid2 = st.columns(2)
    with c_vid1:
        st.subheader("Original")
        st.video(video_file)
    with c_vid2:
        st.subheader("With Predicted Frames")
        # TODO: point to the file generated by ffmpeg
        st.info("Click 'Process' to generate AI version...")
        if st.button("Generate AI Video"):
            st.warning("Processing all triplets... this will take a minute.")
            # TODO: ffmpeg loop goes here
